# Generated by Django 3.2.9 on 2022-01-19 06:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0006_alter_exam_year'),
        ('student', '0015_alter_examdetails_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subname', models.CharField(default='--', max_length=50)),
                ('date', models.DateField(default=datetime.date(2022, 1, 19))),
                ('obtained_marks', models.IntegerField(default=0)),
                ('user_name', models.CharField(default='Na', max_length=20)),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examdetailsexamid', to='teacher.exam')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attemptedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('exam_id', 'student_id')},
            },
        ),
        migrations.CreateModel(
            name='OnExamDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('markedques', models.CharField(max_length=70)),
                ('minutes', models.IntegerField()),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examdetails', to='teacher.exam')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('exam_id', 'student_id')},
            },
        ),
        migrations.DeleteModel(
            name='Examdetails',
        ),
    ]
