# Generated by Django 3.2.9 on 2022-01-21 03:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_rename_user_name_examresult_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='date',
            field=models.DateField(default=datetime.date(2022, 1, 21)),
        ),
    ]
