# Generated by Django 3.2.9 on 2022-01-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_alter_examresult_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='onexamdetail',
            name='marksupdate',
            field=models.IntegerField(default=0),
        ),
    ]
