# Generated by Django 3.2.9 on 2022-01-23 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_onexamdetail_marksupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='date',
            field=models.DateField(default=datetime.date(2022, 1, 23)),
        ),
    ]
