# Generated by Django 3.2.9 on 2022-01-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_alter_exam_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='id2',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='questions',
            name='correctoption',
            field=models.IntegerField(default=2),
        ),
    ]
