# Generated by Django 3.2.9 on 2022-01-21 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_auto_20220121_0920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='id2',
            new_name='browsetime',
        ),
    ]
