# Generated by Django 3.2.9 on 2022-01-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_rename_id2_questions_browsetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='correctoption',
            field=models.IntegerField(default=4),
        ),
    ]
