# Generated by Django 3.2.9 on 2022-01-21 09:14

from django.db import migrations, models
import teacher.models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_alter_questions_correctoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='quesimg',
            field=models.ImageField(blank=True, upload_to=teacher.models.upload_to, verbose_name='Image'),
        ),
    ]
