# Generated by Django 3.2.9 on 2022-01-21 09:49

from django.db import migrations, models
import teacher.models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_questions_quesimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='opt1img',
            field=models.ImageField(blank=True, upload_to=teacher.models.upload_to, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='questions',
            name='opt2img',
            field=models.ImageField(blank=True, upload_to=teacher.models.upload_to, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='questions',
            name='opt3img',
            field=models.ImageField(blank=True, upload_to=teacher.models.upload_to, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='questions',
            name='opt4img',
            field=models.ImageField(blank=True, upload_to=teacher.models.upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='correctoption',
            field=models.IntegerField(default=2),
        ),
    ]
