# Generated by Django 3.2.9 on 2022-01-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_auto_20220121_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='correctoption',
            field=models.IntegerField(default=3),
        ),
    ]
