# Generated by Django 3.2.9 on 2022-01-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_newuser_rel_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='start_date',
        ),
        migrations.AddField(
            model_name='newuser',
            name='randomnum',
            field=models.FloatField(default=0.4369850777348402),
        ),
    ]
