# Generated by Django 3.2.9 on 2022-01-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220119_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='randomnum',
            field=models.FloatField(default=0.6492014224595187),
        ),
    ]
